<?php

/**
 * @file
 * Contains encryption_policy.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function encryption_policy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the encryption_policy module.
    case 'help.page.encryption_policy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Define and enforce encryption standards for your website.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function encryption_policy_theme() {
  $theme = [];

  return $theme;
}

/**
 * Implements hook_menu_links_discovered_alter.
 */
function encryption_policy_menu_links_discovered_alter(&$links) {
  // If password_policy module exists, consolidate admin links under a single Security grouping.
  if (\Drupal::moduleHandler()->moduleExists('password_policy')) {
    $links['encryption_policy.admin']['parent'] = 'password_policy.admin_index';
    unset($links['encryption_policy.admin_index']);
  }
}
