<?php

/**
 * @file
 * Contains \Drupal\encryption_policy\Form\EncryptionPolicyForm.
 */

namespace Drupal\encryption_policy\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Class EncryptionPolicyForm.
 *
 * @package Drupal\encryption_policy\Form
 */
class EncryptionPolicyForm extends ConfigFormBase {

  /**
   * Array listing ciphers.
   */
  private $ciphers;

  /**
   *
   */
  private $whitelistedCiphers;
  private $blacklistedCiphers;
  private $serverSideCiphers;

  /**
   * Constructs an EncryptionPolicyForm object.
   *
   * @param \Drupal\Core\Config\ConfigFactoryInterface $config_factory
   *   The factory for configuration objects.
   */
  public function __construct(ConfigFactoryInterface $config_factory) {
    parent::__construct($config_factory);

    $this->allCiphers = include('../../encryption_policy.all_suites.php');
  }

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'encryption_policy_form';
  }

  /**
   * {@inheritdoc}
   */
  protected function getEditableConfigNames() {
    return ['encryption_policy.settings'];
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    $ciphers = $this->getCiphers();

    // Make keys and values match.
    $options = array_combine($ciphers, $ciphers);

    $form['encryption_policy']['ciphers'] = array(
      '#type' => 'checkboxes',
      '#options' => $options,
      '#title' => t('Options'),
    );

    return parent::buildForm($form, $form_state);
  }

  private function getCiphers() {
    // If specific list of server-side ciphers is available, use that.
    // @TODO

    // Otherwise use full list of TLS Ciphers.
    return $this->getAllTlsCipherSuites();
  }

  /**
   * Returns an array of all cipher suites in the TLS standards.
   *
   * Based on:
   *   https://github.com/jmhodges/howsmyssl/blob/master/all_suites.go
   *
   * Generated with:
   *   curl -s http://www.iana.org/assignments/tls-parameters/tls-parameters.txt | grep '0x.* TLS_' | awk '{ print "\""$2"\","}' | sed 's/,0x//'
   *
   * Plus appending the new ChaCha20/Poly1305 curve ciphers from Chrome 33.0 and
   * the fallback SCSV if the client had to degrade its version of TLS in order
   * to talk to the server. This is currently only in Chrome, and may one day be
   * useful to call out.
   */
  public static function getAllTlsCipherSuites() {
    return array(
      "TLS_NULL_WITH_NULL_NULL",
      "TLS_RSA_WITH_NULL_MD5",
      "TLS_RSA_WITH_NULL_SHA",
      "TLS_RSA_EXPORT_WITH_RC4_40_MD5",
      "TLS_RSA_WITH_RC4_128_MD5",
      "TLS_RSA_WITH_RC4_128_SHA",
      "TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5",
      "TLS_RSA_WITH_IDEA_CBC_SHA",
      "TLS_RSA_EXPORT_WITH_DES40_CBC_SHA",
      "TLS_RSA_WITH_DES_CBC_SHA",
      "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
      "TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA",
      "TLS_DH_DSS_WITH_DES_CBC_SHA",
      "TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA",
      "TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA",
      "TLS_DH_RSA_WITH_DES_CBC_SHA",
      "TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA",
      "TLS_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA",
      "TLS_DHE_DSS_WITH_DES_CBC_SHA",
      "TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA",
      "TLS_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA",
      "TLS_DHE_RSA_WITH_DES_CBC_SHA",
      "TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA",
      "TLS_DH_anon_EXPORT_WITH_RC4_40_MD5",
      "TLS_DH_anon_WITH_RC4_128_MD5",
      "TLS_DH_anon_EXPORT_WITH_DES40_CBC_SHA",
      "TLS_DH_anon_WITH_DES_CBC_SHA",
      "TLS_DH_anon_WITH_3DES_EDE_CBC_SHA",
      "TLS_KRB5_WITH_DES_CBC_SHA",
      "TLS_KRB5_WITH_3DES_EDE_CBC_SHA",
      "TLS_KRB5_WITH_RC4_128_SHA",
      "TLS_KRB5_WITH_IDEA_CBC_SHA",
      "TLS_KRB5_WITH_DES_CBC_MD5",
      "TLS_KRB5_WITH_3DES_EDE_CBC_MD5",
      "TLS_KRB5_WITH_RC4_128_MD5",
      "TLS_KRB5_WITH_IDEA_CBC_MD5",
      "TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA",
      "TLS_KRB5_EXPORT_WITH_RC2_CBC_40_SHA",
      "TLS_KRB5_EXPORT_WITH_RC4_40_SHA",
      "TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5",
      "TLS_KRB5_EXPORT_WITH_RC2_CBC_40_MD5",
      "TLS_KRB5_EXPORT_WITH_RC4_40_MD5",
      "TLS_PSK_WITH_NULL_SHA",
      "TLS_DHE_PSK_WITH_NULL_SHA",
      "TLS_RSA_PSK_WITH_NULL_SHA",
      "TLS_RSA_WITH_AES_128_CBC_SHA",
      "TLS_DH_DSS_WITH_AES_128_CBC_SHA",
      "TLS_DH_RSA_WITH_AES_128_CBC_SHA",
      "TLS_DHE_DSS_WITH_AES_128_CBC_SHA",
      "TLS_DHE_RSA_WITH_AES_128_CBC_SHA",
      "TLS_DH_anon_WITH_AES_128_CBC_SHA",
      "TLS_RSA_WITH_AES_256_CBC_SHA",
      "TLS_DH_DSS_WITH_AES_256_CBC_SHA",
      "TLS_DH_RSA_WITH_AES_256_CBC_SHA",
      "TLS_DHE_DSS_WITH_AES_256_CBC_SHA",
      "TLS_DHE_RSA_WITH_AES_256_CBC_SHA",
      "TLS_DH_anon_WITH_AES_256_CBC_SHA",
      "TLS_RSA_WITH_NULL_SHA256",
      "TLS_RSA_WITH_AES_128_CBC_SHA256",
      "TLS_RSA_WITH_AES_256_CBC_SHA256",
      "TLS_DH_DSS_WITH_AES_128_CBC_SHA256",
      "TLS_DH_RSA_WITH_AES_128_CBC_SHA256",
      "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256",
      "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA",
      "TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA",
      "TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA",
      "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA",
      "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA",
      "TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA",
      "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256",
      "TLS_DH_DSS_WITH_AES_256_CBC_SHA256",
      "TLS_DH_RSA_WITH_AES_256_CBC_SHA256",
      "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256",
      "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256",
      "TLS_DH_anon_WITH_AES_128_CBC_SHA256",
      "TLS_DH_anon_WITH_AES_256_CBC_SHA256",
      "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA",
      "TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA",
      "TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA",
      "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA",
      "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA",
      "TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA",
      "TLS_PSK_WITH_RC4_128_SHA",
      "TLS_PSK_WITH_3DES_EDE_CBC_SHA",
      "TLS_PSK_WITH_AES_128_CBC_SHA",
      "TLS_PSK_WITH_AES_256_CBC_SHA",
      "TLS_DHE_PSK_WITH_RC4_128_SHA",
      "TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA",
      "TLS_DHE_PSK_WITH_AES_128_CBC_SHA",
      "TLS_DHE_PSK_WITH_AES_256_CBC_SHA",
      "TLS_RSA_PSK_WITH_RC4_128_SHA",
      "TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA",
      "TLS_RSA_PSK_WITH_AES_128_CBC_SHA",
      "TLS_RSA_PSK_WITH_AES_256_CBC_SHA",
      "TLS_RSA_WITH_SEED_CBC_SHA",
      "TLS_DH_DSS_WITH_SEED_CBC_SHA",
      "TLS_DH_RSA_WITH_SEED_CBC_SHA",
      "TLS_DHE_DSS_WITH_SEED_CBC_SHA",
      "TLS_DHE_RSA_WITH_SEED_CBC_SHA",
      "TLS_DH_anon_WITH_SEED_CBC_SHA",
      "TLS_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_DH_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_DH_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_DHE_DSS_WITH_AES_128_GCM_SHA256",
      "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384",
      "TLS_DH_DSS_WITH_AES_128_GCM_SHA256",
      "TLS_DH_DSS_WITH_AES_256_GCM_SHA384",
      "TLS_DH_anon_WITH_AES_128_GCM_SHA256",
      "TLS_DH_anon_WITH_AES_256_GCM_SHA384",
      "TLS_PSK_WITH_AES_128_GCM_SHA256",
      "TLS_PSK_WITH_AES_256_GCM_SHA384",
      "TLS_DHE_PSK_WITH_AES_128_GCM_SHA256",
      "TLS_DHE_PSK_WITH_AES_256_GCM_SHA384",
      "TLS_RSA_PSK_WITH_AES_128_GCM_SHA256",
      "TLS_RSA_PSK_WITH_AES_256_GCM_SHA384",
      "TLS_PSK_WITH_AES_128_CBC_SHA256",
      "TLS_PSK_WITH_AES_256_CBC_SHA384",
      "TLS_PSK_WITH_NULL_SHA256",
      "TLS_PSK_WITH_NULL_SHA384",
      "TLS_DHE_PSK_WITH_AES_128_CBC_SHA256",
      "TLS_DHE_PSK_WITH_AES_256_CBC_SHA384",
      "TLS_DHE_PSK_WITH_NULL_SHA256",
      "TLS_DHE_PSK_WITH_NULL_SHA384",
      "TLS_RSA_PSK_WITH_AES_128_CBC_SHA256",
      "TLS_RSA_PSK_WITH_AES_256_CBC_SHA384",
      "TLS_RSA_PSK_WITH_NULL_SHA256",
      "TLS_RSA_PSK_WITH_NULL_SHA384",
      "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_DH_DSS_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_DH_RSA_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256",
      "TLS_DH_DSS_WITH_CAMELLIA_256_CBC_SHA256",
      "TLS_DH_RSA_WITH_CAMELLIA_256_CBC_SHA256",
      "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA256",
      "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256",
      "TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256",
      "TLS_EMPTY_RENEGOTIATION_INFO_SCSV",
      "TLS_FALLBACK_SCSV",
      "TLS_ECDH_ECDSA_WITH_NULL_SHA",
      "TLS_ECDH_ECDSA_WITH_RC4_128_SHA",
      "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA",
      "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA",
      "TLS_ECDHE_ECDSA_WITH_NULL_SHA",
      "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA",
      "TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
      "TLS_ECDH_RSA_WITH_NULL_SHA",
      "TLS_ECDH_RSA_WITH_RC4_128_SHA",
      "TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA",
      "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_NULL_SHA",
      "TLS_ECDHE_RSA_WITH_RC4_128_SHA",
      "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
      "TLS_ECDH_anon_WITH_NULL_SHA",
      "TLS_ECDH_anon_WITH_RC4_128_SHA",
      "TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA",
      "TLS_ECDH_anon_WITH_AES_128_CBC_SHA",
      "TLS_ECDH_anon_WITH_AES_256_CBC_SHA",
      "TLS_SRP_SHA_WITH_3DES_EDE_CBC_SHA",
      "TLS_SRP_SHA_RSA_WITH_3DES_EDE_CBC_SHA",
      "TLS_SRP_SHA_DSS_WITH_3DES_EDE_CBC_SHA",
      "TLS_SRP_SHA_WITH_AES_128_CBC_SHA",
      "TLS_SRP_SHA_RSA_WITH_AES_128_CBC_SHA",
      "TLS_SRP_SHA_DSS_WITH_AES_128_CBC_SHA",
      "TLS_SRP_SHA_WITH_AES_256_CBC_SHA",
      "TLS_SRP_SHA_RSA_WITH_AES_256_CBC_SHA",
      "TLS_SRP_SHA_DSS_WITH_AES_256_CBC_SHA",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384",
      "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384",
      "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256",
      "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_PSK_WITH_RC4_128_SHA",
      "TLS_ECDHE_PSK_WITH_3DES_EDE_CBC_SHA",
      "TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA",
      "TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA",
      "TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256",
      "TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA384",
      "TLS_ECDHE_PSK_WITH_NULL_SHA",
      "TLS_ECDHE_PSK_WITH_NULL_SHA256",
      "TLS_ECDHE_PSK_WITH_NULL_SHA384",
      "TLS_RSA_WITH_ARIA_128_CBC_SHA256",
      "TLS_RSA_WITH_ARIA_256_CBC_SHA384",
      "TLS_DH_DSS_WITH_ARIA_128_CBC_SHA256",
      "TLS_DH_DSS_WITH_ARIA_256_CBC_SHA384",
      "TLS_DH_RSA_WITH_ARIA_128_CBC_SHA256",
      "TLS_DH_RSA_WITH_ARIA_256_CBC_SHA384",
      "TLS_DHE_DSS_WITH_ARIA_128_CBC_SHA256",
      "TLS_DHE_DSS_WITH_ARIA_256_CBC_SHA384",
      "TLS_DHE_RSA_WITH_ARIA_128_CBC_SHA256",
      "TLS_DHE_RSA_WITH_ARIA_256_CBC_SHA384",
      "TLS_DH_anon_WITH_ARIA_128_CBC_SHA256",
      "TLS_DH_anon_WITH_ARIA_256_CBC_SHA384",
      "TLS_ECDHE_ECDSA_WITH_ARIA_128_CBC_SHA256",
      "TLS_ECDHE_ECDSA_WITH_ARIA_256_CBC_SHA384",
      "TLS_ECDH_ECDSA_WITH_ARIA_128_CBC_SHA256",
      "TLS_ECDH_ECDSA_WITH_ARIA_256_CBC_SHA384",
      "TLS_ECDHE_RSA_WITH_ARIA_128_CBC_SHA256",
      "TLS_ECDHE_RSA_WITH_ARIA_256_CBC_SHA384",
      "TLS_ECDH_RSA_WITH_ARIA_128_CBC_SHA256",
      "TLS_ECDH_RSA_WITH_ARIA_256_CBC_SHA384",
      "TLS_RSA_WITH_ARIA_128_GCM_SHA256",
      "TLS_RSA_WITH_ARIA_256_GCM_SHA384",
      "TLS_DHE_RSA_WITH_ARIA_128_GCM_SHA256",
      "TLS_DHE_RSA_WITH_ARIA_256_GCM_SHA384",
      "TLS_DH_RSA_WITH_ARIA_128_GCM_SHA256",
      "TLS_DH_RSA_WITH_ARIA_256_GCM_SHA384",
      "TLS_DHE_DSS_WITH_ARIA_128_GCM_SHA256",
      "TLS_DHE_DSS_WITH_ARIA_256_GCM_SHA384",
      "TLS_DH_DSS_WITH_ARIA_128_GCM_SHA256",
      "TLS_DH_DSS_WITH_ARIA_256_GCM_SHA384",
      "TLS_DH_anon_WITH_ARIA_128_GCM_SHA256",
      "TLS_DH_anon_WITH_ARIA_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_ARIA_256_GCM_SHA384",
      "TLS_ECDH_ECDSA_WITH_ARIA_128_GCM_SHA256",
      "TLS_ECDH_ECDSA_WITH_ARIA_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_ARIA_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_ARIA_256_GCM_SHA384",
      "TLS_ECDH_RSA_WITH_ARIA_128_GCM_SHA256",
      "TLS_ECDH_RSA_WITH_ARIA_256_GCM_SHA384",
      "TLS_PSK_WITH_ARIA_128_CBC_SHA256",
      "TLS_PSK_WITH_ARIA_256_CBC_SHA384",
      "TLS_DHE_PSK_WITH_ARIA_128_CBC_SHA256",
      "TLS_DHE_PSK_WITH_ARIA_256_CBC_SHA384",
      "TLS_RSA_PSK_WITH_ARIA_128_CBC_SHA256",
      "TLS_RSA_PSK_WITH_ARIA_256_CBC_SHA384",
      "TLS_PSK_WITH_ARIA_128_GCM_SHA256",
      "TLS_PSK_WITH_ARIA_256_GCM_SHA384",
      "TLS_DHE_PSK_WITH_ARIA_128_GCM_SHA256",
      "TLS_DHE_PSK_WITH_ARIA_256_GCM_SHA384",
      "TLS_RSA_PSK_WITH_ARIA_128_GCM_SHA256",
      "TLS_RSA_PSK_WITH_ARIA_256_GCM_SHA384",
      "TLS_ECDHE_PSK_WITH_ARIA_128_CBC_SHA256",
      "TLS_ECDHE_PSK_WITH_ARIA_256_CBC_SHA384",
      "TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_CBC_SHA384",
      "TLS_ECDH_ECDSA_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_ECDH_ECDSA_WITH_CAMELLIA_256_CBC_SHA384",
      "TLS_ECDHE_RSA_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_ECDHE_RSA_WITH_CAMELLIA_256_CBC_SHA384",
      "TLS_ECDH_RSA_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_ECDH_RSA_WITH_CAMELLIA_256_CBC_SHA384",
      "TLS_RSA_WITH_CAMELLIA_128_GCM_SHA256",
      "TLS_RSA_WITH_CAMELLIA_256_GCM_SHA384",
      "TLS_DHE_RSA_WITH_CAMELLIA_128_GCM_SHA256",
      "TLS_DHE_RSA_WITH_CAMELLIA_256_GCM_SHA384",
      "TLS_DH_RSA_WITH_CAMELLIA_128_GCM_SHA256",
      "TLS_DH_RSA_WITH_CAMELLIA_256_GCM_SHA384",
      "TLS_DHE_DSS_WITH_CAMELLIA_128_GCM_SHA256",
      "TLS_DHE_DSS_WITH_CAMELLIA_256_GCM_SHA384",
      "TLS_DH_DSS_WITH_CAMELLIA_128_GCM_SHA256",
      "TLS_DH_DSS_WITH_CAMELLIA_256_GCM_SHA384",
      "TLS_DH_anon_WITH_CAMELLIA_128_GCM_SHA256",
      "TLS_DH_anon_WITH_CAMELLIA_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_GCM_SHA384",
      "TLS_ECDH_ECDSA_WITH_CAMELLIA_128_GCM_SHA256",
      "TLS_ECDH_ECDSA_WITH_CAMELLIA_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_CAMELLIA_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_CAMELLIA_256_GCM_SHA384",
      "TLS_ECDH_RSA_WITH_CAMELLIA_128_GCM_SHA256",
      "TLS_ECDH_RSA_WITH_CAMELLIA_256_GCM_SHA384",
      "TLS_PSK_WITH_CAMELLIA_128_GCM_SHA256",
      "TLS_PSK_WITH_CAMELLIA_256_GCM_SHA384",
      "TLS_DHE_PSK_WITH_CAMELLIA_128_GCM_SHA256",
      "TLS_DHE_PSK_WITH_CAMELLIA_256_GCM_SHA384",
      "TLS_RSA_PSK_WITH_CAMELLIA_128_GCM_SHA256",
      "TLS_RSA_PSK_WITH_CAMELLIA_256_GCM_SHA384",
      "TLS_PSK_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_PSK_WITH_CAMELLIA_256_CBC_SHA384",
      "TLS_DHE_PSK_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_DHE_PSK_WITH_CAMELLIA_256_CBC_SHA384",
      "TLS_RSA_PSK_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_RSA_PSK_WITH_CAMELLIA_256_CBC_SHA384",
      "TLS_ECDHE_PSK_WITH_CAMELLIA_128_CBC_SHA256",
      "TLS_ECDHE_PSK_WITH_CAMELLIA_256_CBC_SHA384",
      "TLS_RSA_WITH_AES_128_CCM",
      "TLS_RSA_WITH_AES_256_CCM",
      "TLS_DHE_RSA_WITH_AES_128_CCM",
      "TLS_DHE_RSA_WITH_AES_256_CCM",
      "TLS_RSA_WITH_AES_128_CCM_8",
      "TLS_RSA_WITH_AES_256_CCM_8",
      "TLS_DHE_RSA_WITH_AES_128_CCM_8",
      "TLS_DHE_RSA_WITH_AES_256_CCM_8",
      "TLS_PSK_WITH_AES_128_CCM",
      "TLS_PSK_WITH_AES_256_CCM",
      "TLS_DHE_PSK_WITH_AES_128_CCM",
      "TLS_DHE_PSK_WITH_AES_256_CCM",
      "TLS_PSK_WITH_AES_128_CCM_8",
      "TLS_PSK_WITH_AES_256_CCM_8",
      "TLS_PSK_DHE_WITH_AES_128_CCM_8",
      "TLS_PSK_DHE_WITH_AES_256_CCM_8",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CCM",
      "TLS_ECDHE_ECDSA_WITH_AES_256_CCM",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8",
      "TLS_ECDHE_ECDSA_WITH_AES_256_CCM_8",

      "TLS_FALLBACK_SCSV",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
      "TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256",

      // http://tools.ietf.org/html/draft-ietf-tls-56-bit-ciphersuites-01
      "TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA",
      "TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA",
      "TLS_RSA_EXPORT1024_WITH_RC4_56_SHA",
      "TLS_DHE_DSS_EXPORT1024_WITH_RC4_56_SHA",
      "TLS_DHE_DSS_WITH_RC4_128_SHA", // 128-bit RC4, not 56-bit
    );
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $this->config('encryption_policy.settings')
      ->set('element', $form_state['values']['encryption_policy']['ciphers'])
      ->save();

    parent::submitForm($form, $form_state);
  }


}
